---
- name: Create users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password | default('!') }}"
    groups: "{{ item.groups | default(omit) }}"
    comment: "{{ item.description | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    shell: "{{ item.shell | default(users_shell) }}"
    home: "{{ item.home_directory | default('/home/' + item.username) }}"
    append: "{{ item.append_to_groups | default(users_append_to_groups) }}"
    create_home: "{{ item.create_home_directory | default(users_create_home_directory) }}"
    update_password: "{{ item.update_password | default(users_update_password) | ternary('always', 'on_create') }}"
  loop: "{{ users_to_create }}"

- name: Remove users
  user:
    name: "{{ item.username }}"
    state: absent
    remove: "{{ item.remove_user_directories | default(users_remove_user_directories) }}"
    force: "{{ item.force_force_remove | default(users_force_remove) }}"
  loop: "{{ users_to_remove }}"

- name: Add SSH authorized keys for users
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ lookup('file', item.1) }}"
    path: "{{ item.0.home_directory | default('/home/' + item.0.username) }}/{{ users_authorized_key_file }}"
  when: >
    item.0.create_home_directory is undefined or
    item.0.create_home_directory | bool
  loop: "{{ users_to_create | subelements('ssh_keys', skip_missing=True) }}"

- name: Customise user profile
  blockinfile:
    block: "{{ item.profile }}"
    path: "{{ item.home_directory | default('/home/' + item.username) }}/{{ users_profile_file }}"
    create: yes
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0644
  when: >
    (item.create_home_directory is undefined or item.create_home_directory | bool) and
    item.profile is defined
  loop: "{{ users_to_create }}"

- name: Add users to sudoers
  template:
    src: sudoers-user.j2
    dest: "{{ users_sudoers_directory_path }}/99-{{ item.username }}"
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s
  loop: "{{ users_sudoers }}"